/**
 * This file is part of Autolycus.
 * Copyright 2010 Joseph Jon Booker.
 *
 * Autolycus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * Autolycus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Autolycus.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.neoturbine.autolycus.internal;

import android.util.Log;

public class BusTimeError extends Exception {
	private static final long serialVersionUID = 5903785755487896094L;
	// add fields as they become possible in used api calls
	private String msg;
	private int stpid;
	private int vid;
	private String rt;
	private String dir;

	public BusTimeError() {// default constructor
		super();
	}

	public void setField(String name, String value) {
		if (name.equals("msg"))
			setMessage(value);
		else if (name.equals("stpid"))
			setStopID(Integer.parseInt(value));
		else if (name.equals("vid"))
			setVid(Integer.parseInt(value));
		else if (name.equals("rt"))
			setRoute(value);
		else if (name.equals("dir") || name.equals("rtdir"))
			setDirection(value);
		else
			Log.w("Bus Track", "Unknown in BusTimeError object: " + name
					+ " = " + value);
	}

	// generated by eclipse
	@Override
	public String getMessage() {
		return msg;
	}

	public void setMessage(String msg) {
		this.msg = msg;
	}

	public int getStopID() {
		return stpid;
	}

	public void setStopID(int stpid) {
		this.stpid = stpid;
	}

	public int getVid() {
		return vid;
	}

	public void setVid(int vid) {
		this.vid = vid;
	}

	public String getRoute() {
		return rt;
	}

	public void setRoute(String rt) {
		this.rt = rt;
	}

	public String getDirection() {
		return dir;
	}

	public void setDirection(String dir) {
		this.dir = dir;
	}

	@Override
	public String toString() {
		return getMessage();
	}

}
