package net.neoturbine.autolycus.internal;

import android.util.Log;

public class BusTimeError extends Exception {
	private static final long serialVersionUID = 5903785755487896094L;
	//add fields as they become possible in used api calls
	private String msg;
	private int stpid;
	private int vid;
	private String rt;
	private String dir;

	public BusTimeError() {//default constructor
		super();		
	} 
	
	public void setField(String name, String value) {
		if(name.equals("msg"))
			setMessage(value);
		else if (name.equals("stpid"))
			setStopID(Integer.parseInt(value));
		else if (name.equals("vid"))
			setVid(Integer.parseInt(value));
		else if (name.equals("rt"))
			setRoute(value);
		else if (name.equals("dir") || name.equals("rtdir"))
			setDirection(value);
		else
			Log.w("Bus Track", "Unknown in BusTimeError object: "+name+" = "+value);
	}
	
	//generated by eclipse
	@Override
	public String getMessage() {
		return msg;
	}
	public void setMessage(String msg) {
		this.msg = msg;
	}
	public int getStopID() {
		return stpid;
	}
	public void setStopID(int stpid) {
		this.stpid = stpid;
	}
	public int getVid() {
		return vid;
	}
	public void setVid(int vid) {
		this.vid = vid;
	}
	public String getRoute() {
		return rt;
	}
	public void setRoute(String rt) {
		this.rt = rt;
	}
	public String getDirection() {
		return dir;
	}
	public void setDirection(String dir) {
		this.dir = dir;
	}
	
	public String toString() {
		return getMessage();
	}

}
