/**
 * This file is part of Autolycus.
 * Copyright 2010 Joseph Jon Booker.
 *
 * Autolycus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * Autolycus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Autolycus.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.neoturbine.autolycus.internal;

import java.io.Serializable;
import android.util.Log;

//final for efficiency
final class StopInfoBuilder implements Serializable {
	private static final long serialVersionUID = -6247913982038105829L;
	private String system;
	private String rt;
	private String dir;
	private String stpnm;
	private int stpid;
	private double lat; // both in WGS 84
	private double lon;

	public StopInfoBuilder(String system) {
		setSystem(system);
	}

	/* Setters and Getters.... generated by eclipse */
	public void setSystem(String system) {
		this.system = system;
	}

	public String getSystem() {
		return system;
	}

	public void setRoute(String rt) {
		this.rt = rt;
	}

	public String getRoute() {
		return rt;
	}

	public void setDir(String dir) {
		this.dir = dir;
	}

	public String getDir() {
		return dir;
	}

	public void setName(String stpnm) {
		this.stpnm = stpnm;
	}

	public String getName() {
		return stpnm;
	}

	public void setStopID(int stpid) {
		this.stpid = stpid;
	}

	public int getStopID() {
		return stpid;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public double getLat() {
		return lat;
	}

	public void setLong(double lon) {
		this.lon = lon;
	}

	public double getLong() {
		return lon;
	}

	/* nice little helper function */
	@Override
	public String toString() {
		return getSystem() + " Stop \"" + getName() + "\" (" + getStopID()
				+ "), " + getDir() + " on Route " + getRoute() + ".";
	}

	public void setField(String name, String value) {
		if (name.equals("stpnm"))
			setName(value);
		else if (name.equals("stpid"))
			setStopID(Integer.parseInt(value));
		else if (name.equals("rt"))
			setRoute(value);
		else if (name.equals("lat"))
			setLat(Double.parseDouble(value));
		else if (name.equals("lon"))
			setLong(Double.parseDouble(value));
		else
			Log.w("Bus Track", "Unknown in StopInfo object: " + name + " = "
					+ value);
	}

	public StopInfo toStopInfo() {
		return new StopInfo(system, rt, dir, stpnm, stpid, lat, lon);
	}

}
